---
abstract: 'Make sure that pictures cope with the MOBI standards.'
author:
  - 'Boris Däppen <boris_daeppen@bluewin.ch>'
build_requires: {}
configure_requires:
  ExtUtils::MakeMaker: 6.30
dynamic_config: 0
generated_by: 'Dist::Zilla version 4.300029, CPAN::Meta::Converter version 2.120921'
license: artistic_2
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: EBook-MOBI-Image
requires:
  File::Basename: 0
  File::Temp: 0
  Image::Imlib2: 0
version: 0.12
